### ISSUE TITLE
setup.py doesn't install numpy

### ISSUE THREAD

**Issue by ulf1** [klb2/qmkpy#3]
**Describe the bug**

```
Processing /Users/uh/projects/misc/qmkpy
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/uh/projects/misc/qmkpy/setup.py", line 3, in <module>
          from qmkpy import __version__, __author__, __email__
        File "/Users/uh/projects/misc/qmkpy/qmkpy/__init__.py", line 6, in <module>
          from . import algorithms
        File "/Users/uh/projects/misc/qmkpy/qmkpy/algorithms.py", line 3, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**To Reproduce**
Follow https://github.com/klb2/qmkpy#installation
```
git clone https://github.com/klb2/qmkpy.git
cd qmkpy
# stay in main branch

python3 -m venv .venv                      
source .venv/bin/activate
pip3 install --upgrade pip

# error happens here
pip3 install .
```

**Expected behavior**
Successful installation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Version Python 3.7.9
 - Versions of required packages: numpy 1.21.6

**Additional context**
The quick fix would be to run 
`pip3 install -r requirements.txt`
before 
`pip3 install .`

**Comment by ulf1** [comment]
`pytest` wasn't installed as well due to the same error
